apply plugin: 'com.android.application'

android { namespace 'com.mibox.os'; compileSdk 35
    signingConfigs { debug { enableV1Signing true; enableV2Signing true } }
    defaultConfig { applicationId 'com.mibox.os'; minSdk 23; targetSdk 35; versionCode 19; versionName '1.2.1-qtv' }
    buildTypes { debug { signingConfig signingConfigs.debug } }
}
